### ISSUE TITLE
Config UI Crash

### ISSUE THREAD

**Issue by A5ho9999** [wisp-forest/owo-lib#128]
Attempting to backspace the Color input inside the Config will crash the game.

```
Time: 2023-05-09 17:30:10
Description: keyPressed event handler

java.lang.NumberFormatException: For input string: "" under radix 16
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:861)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$14(OptionComponentFactory.java:77)
	at io.wispforest.owo.config.ui.component.ConfigTextBox.parsedValue(ConfigTextBox.java:65)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$16(OptionComponentFactory.java:82)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$17(OptionComponentFactory.java:88)
	at io.wispforest.owo.ui.component.TextBoxComponent$OnChanged.lambda$newStream$0(TextBoxComponent.java:84)
	at io.wispforest.owo.util.Observable.notifyObservers(Observable.java:97)
	at io.wispforest.owo.util.Observable.set(Observable.java:83)
	at net.minecraft.class_342.handler$cha000$owo$callOwoListener(class_342.java:1681)
	at net.minecraft.class_342.method_1874(class_342.java)
	at net.minecraft.class_342.method_1883(class_342.java:255)
	at net.minecraft.class_342.method_1878(class_342.java:199)
	at net.minecraft.class_342.method_16873(class_342.java:157)
	at net.minecraft.class_342.method_25404(class_342.java:318)
	at io.wispforest.owo.ui.component.VanillaWidgetComponent.onKeyPress(VanillaWidgetComponent.java:157)
	at net.minecraft.class_339.onKeyPress(class_339.java:1710)
	at io.wispforest.owo.ui.base.BaseParentComponent.onKeyPress(BaseParentComponent.java:250)
	at io.wispforest.owo.ui.core.OwoUIAdapter.method_25404(OwoUIAdapter.java:250)
	at io.wispforest.owo.ui.base.BaseOwoScreen.method_25404(BaseOwoScreen.java:114)
	at io.wispforest.owo.config.ui.ConfigScreen.method_25404(ConfigScreen.java:418)
	at net.minecraft.class_309.method_1454(class_309.java:394)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_309.method_1466(class_309.java:390)
	at net.minecraft.class_309.method_22678(class_309.java:478)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:478)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:234)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

```
-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:861)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$14(OptionComponentFactory.java:77)
	at io.wispforest.owo.config.ui.component.ConfigTextBox.parsedValue(ConfigTextBox.java:65)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$16(OptionComponentFactory.java:82)
	at io.wispforest.owo.config.ui.OptionComponentFactory.lambda$static$17(OptionComponentFactory.java:88)
	at io.wispforest.owo.ui.component.TextBoxComponent$OnChanged.lambda$newStream$0(TextBoxComponent.java:84)
	at io.wispforest.owo.util.Observable.notifyObservers(Observable.java:97)
	at io.wispforest.owo.util.Observable.set(Observable.java:83)
	at net.minecraft.class_342.handler$cke000$owo$callOwoListener(class_342.java:1692)
	at net.minecraft.class_342.method_1874(class_342.java)
	at net.minecraft.class_342.method_1883(class_342.java:258)
	at net.minecraft.class_342.method_1878(class_342.java:202)
	at net.minecraft.class_342.method_16873(class_342.java:160)
	at net.minecraft.class_342.method_25404(class_342.java:321)
	at io.wispforest.owo.ui.component.VanillaWidgetComponent.onKeyPress(VanillaWidgetComponent.java:157)
	at net.minecraft.class_339.onKeyPress(class_339.java:1713)
	at io.wispforest.owo.ui.base.BaseParentComponent.onKeyPress(BaseParentComponent.java:250)
	at io.wispforest.owo.ui.core.OwoUIAdapter.method_25404(OwoUIAdapter.java:242)
	at io.wispforest.owo.ui.base.BaseOwoScreen.method_25404(BaseOwoScreen.java:114)
	at io.wispforest.owo.config.ui.ConfigScreen.method_25404(ConfigScreen.java:418)
	at net.minecraft.class_309.method_1454(class_309.java:371)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_309.method_1466(class_309.java:367)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
```
```
-- Affected screen --
Details:
	Screen name: io.wispforest.owo.config.ui.ConfigScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_309.method_1466(class_309.java:367)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by cheapvrplayer** [comment]
i also have this issue
