### ISSUE TITLE
Server crashes with owo-lib. Other mod is requiring owo-lib. java.lang.NoSuchFieldError: CONFIG_SCREEN_PROVIDERS

### ISSUE THREAD

**Issue by weegeeday** [wisp-forest/owo-lib#218]
Sever is crashing with  owo-lib installed.
Fabric 1.19.2, owo-lib v0.8.5.

`[12:09:04] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: CONFIG_SCREEN_PROVIDERS
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.6.jar:?]
Caused by: java.lang.NoSuchFieldError: CONFIG_SCREEN_PROVIDERS
	at io.wispforest.owo.config.ConfigWrapper.<clinit>(ConfigWrapper.java:52) ~[owo-lib-0.8.5+1.19.jar:?]
	at wraith.fwaystones.FabricWaystones.<clinit>(FabricWaystones.java:29) ~[wraith-waystones-3.0.8+mc1.19.2.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.6.jar:?]
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) ~[supermartijn642corelib-1.1.17-fabric-mc1.19.2.jar:?]
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:67) ~[supermartijn642corelib-1.1.17-fabric-mc1.19.2.jar:?]
	at net.minecraft.server.Main.handler$bee000$supermartijn642corelib$beforeInit(Main.java:2526) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 3 more
`

**Comment by Noaaan** [comment]
This crash is usually caused by a change that happened with Fabric Loader 0.15.0, which removes/crashes the game when a mod labels something wrongly (I.E. wrongly labels code as client-only, when it is used on a server). 
I suggest trying to downgrade loader, or report this to Fabric Waystones. I am unsure whether this crash happens specifically due to owo-lib or FWaystones
