### ISSUE TITLE
Error in output

### ISSUE THREAD

**Issue by IAMGROOTYBOI** [wisp-forest/owo-lib#251]
[00:02:20] [Render thread/ERROR]:
 An owo-ui error has occurred during the initial resource reload (on thread Render thread). This is likely a bug caused by *some* other mod initializing an owo-config screen significantly too early - please report it at https://github.com/wisp-forest/owo-lib/issues
	at io.wispforest.owo.ui.util.UIErrorToast.logErrorsDuringInitialLoad(UIErrorToast.java:66) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.util.UIErrorToast.report(UIErrorToast.java:54) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseUIModelScreen$DataSource$AssetDataSource.reportError(BaseUIModelScreen.java:142) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseUIModelScreen.<init>(BaseUIModelScreen.java:43) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.config.ui.ConfigScreen.<init>(ConfigScreen.java:77) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.config.ui.ConfigScreen.createWithCustomModel(ConfigScreen.java:103) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.config.ConfigWrapper.lambda$new$6(ConfigWrapper.java:93) ~[owo-lib-0.12.10+1.21.jar:?]
[00:02:20] [Render thread/ERROR]:
 An owo-ui error has occurred during the initial resource reload (on thread Render thread). This is likely a bug caused by *some* other mod initializing an owo-config screen significantly too early - please report it at https://github.com/wisp-forest/owo-lib/issues
	at io.wispforest.owo.ui.util.UIErrorToast.logErrorsDuringInitialLoad(UIErrorToast.java:66) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.util.UIErrorToast.report(UIErrorToast.java:54) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseUIModelScreen$DataSource$AssetDataSource.reportError(BaseUIModelScreen.java:142) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseUIModelScreen.<init>(BaseUIModelScreen.java:43) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.config.ui.ConfigScreen.<init>(ConfigScreen.java:77) ~[owo-lib-0.12.10+1.21.jar:?]

**Comment by gliscowo** [comment]
Thank you for reporting, but we need your entire `latest.log` file from the run where this occurred in order to try and help. Could you please send it over?

Cheers

**Comment by IAMGROOTYBOI** [comment]
https://mclo.gs/2yPalK2

**Comment by gliscowo** [comment]
Did you do anything at the time the error occurred / to cause it? According to the log you pressed the ModMenu button about 5 seconds before the game even finished loading which seems... unlikely

**Comment by IAMGROOTYBOI** [comment]
No, it just popped on my screen saying an error has occurred with owo:config

**Comment by gliscowo** [comment]
Another question, can you reproduce the issue? We've had many people report this problem in the past (which is why it now generates such a detailed error message) but none of them were able to consistently make it happen which is why we never got around to actually debugging it. If you can (and could somehow give us your modpack setup) that would be most convenient

**Comment by IAMGROOTYBOI** [comment]
Oh, I just realised that it was due to me pressing the mod button before it was loaded in! (I have the no loading screen mod)
