### ISSUE TITLE
Render Overlay crash without Immediately Fast installed

### ISSUE THREAD

**Issue by Barerock** [wisp-forest/owo-lib#318]
Forge: 47.3.0
owo: 0.11.2
Connector: 1.0.0 beta 46

My game was starting fine for the past 3 days, I did absolutely nothing at all to it, and now 12 times in a row it's crashed like this. I disabled IF and the issue still occurs. I was even working on it earlier and it started just fine THREE times in a row. This very much seems like an owo problem at this point, since literally nothing else seems to instigate rendering issues like this with other mods like IF.

It's also extremely hard to test since sometimes it will do this, crash 30 times in a row, and other times I won't crash for three weeks straight with the same mod list. A test instance could crash every time I load it up until I remove owo or it could not care at all with every single mod loaded. Trust me, I've done BOTH of these things with and without my mod list, adding 5s, 10s, 25s of mods at a time dozens of times for months now and I get the same exact amorphous results every time with and without IF.

So, given I have a mod list of ~300, and also given I've done such extreme testing without any real knowledge gained about owo's tendency to crash, I guess the only real culprits might be Forge or Connector, though Connector usually runs owo just fine and I haven't had a Connector related crash _ever_.

If I run only Connector, IF, and owo on a forge instance they behave fine. I can't find a point where it starts crashing reliably.

logs and list:
[A-ModList.txt](https://github.com/user-attachments/files/17236417/A-ModList.txt)
[latest.log](https://github.com/user-attachments/files/17236419/latest.log)
[crash-2024-10-02_17.56.19-client.txt](https://github.com/user-attachments/files/17236423/crash-2024-10-02_17.56.19-client.txt)

**Comment by Barerock** [comment]
These logs actually point at a different issue, I will provide some that are for the actual crash I am reporting

**Comment by Barerock** [comment]
[crash-2024-10-02_18.17.05-client.txt](https://github.com/user-attachments/files/17236934/crash-2024-10-02_18.17.05-client.txt)
[latest.log](https://github.com/user-attachments/files/17236935/latest.log)

This does have immediately fast enabled, so perhaps it still is that mod. This happened on my second start once I got the game running again. Invalid json config files will cause that render crash to happen, instead of letting the game direct to the actual cause: an nbt being invalid, in this case.

**Comment by Dragon-Seeker** [comment]
The crash of owo is more indicative that some error has occured during resource load and it leads to the entire asset loading to start failing everywhere leading to the owo shader being blamed. The crash report sadly dose not help as it will only show the recent issue and the log shows some errors before asset loading pointing towards possible other mods causing the problem.

For instance this given error seems more problematic as a mod loading value will lead to asset loading problems

```
[18:17:00] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: quark, class org.violetmoon.quark.base.Quark
java.lang.ArrayIndexOutOfBoundsException: Index 388 out of bounds for length 0
	at net.minecraftforge.eventbus.ListenerList.unregister(ListenerList.java:133) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.ListenerList.unregisterAll(ListenerList.java:140) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.unregister(EventBus.java:290) ~[eventbus-6.0.5.jar%2387!/:?]
	at org.violetmoon.zetaimplforge.event.ForgeZetaEventBus.unsubscribeMethod(ForgeZetaEventBus.java:94) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.event.bus.ZetaEventBus.lambda$unsubscribe$1(ZetaEventBus.java:83) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.violetmoon.zeta.event.bus.ZetaEventBus.unsubscribe(ZetaEventBus.java:83) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.module.ZetaModule.setEnabledAndManageSubscriptions(ZetaModule.java:53) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.module.ZetaModule.setEnabled(ZetaModule.java:42) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.config.ConfigManager.setModuleEnabled(ConfigManager.java:165) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.config.ConfigManager.lambda$new$10(ConfigManager.java:116) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at org.violetmoon.zeta.config.ConfigManager.lambda$new$12(ConfigManager.java:115) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.config.ConfigManager.lambda$onReload$13(ConfigManager.java:180) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.violetmoon.zeta.config.ConfigManager.onReload(ConfigManager.java:180) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.zeta.Zeta.loadModules(Zeta.java:142) ~[Zeta-1.0-24.jar%23848!/:1.0-24]
	at org.violetmoon.quark.base.proxy.CommonProxy.start(CommonProxy.java:82) ~[Quark-4.0-460.jar%23768!/:4.0-460]
	at org.violetmoon.quark.base.proxy.ClientProxy.start(ClientProxy.java:55) ~[Quark-4.0-460.jar%23768!/:4.0-460]
	at org.violetmoon.quark.base.Quark.<init>(Quark.java:55) ~[Quark-4.0-460.jar%23768!/:4.0-460]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23852!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23851!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Barerock** [comment]
removing owo resolves the issue; however. That is a severe error that I hadn't paid attention to, since the mod works fine. I'll take it to quark when I have time.
