### ISSUE TITLE
NeoForge 1.21.1 - Crash on Rendering Overlay/Loading Shaders When Spectrum is not Present

### ISSUE THREAD

**Issue by ToxinZangoose** [wisp-forest/owo-lib#327]
Hello,

I have recently been trying to diagnose an issue with my modpack and the log files point to this mod when I try launching.

When launching, owo lib tries to load shaders for Spectrum which is not supported for NeoForge.

Below is the log file for the crash I've been experiencing since I've tried removing 19 mods from this pack.

https://mclo.gs/wDKVGtH 

Thank you for your time!

**Comment by Dragon-Seeker** [comment]
```
[02Nov2024 11:04:06.859] [modloading-worker-0/ERROR] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: Error setting up Curios Compatibility!
java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / lightmanscurrency:wallet_copper]
	at TRANSFORMER/neoforge@21.1.73/net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:103) ~[neoforge-21.1.73-universal.jar#429!/:?]
```
With how neo handles crashing it tends to blame Owo when someone in the mod loading chain crashes. This error shows up before so possibly a issue with such mod

**Comment by ToxinZangoose** [comment]
Tried launching without Lightman's Currency and the issue is still present.

**Comment by Dragon-Seeker** [comment]
Also possibly this error as well:
```
	[02Nov2024 11:04:07.644] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: everycomp, class net.mehvahdjukaar.every_compat.neoforge.EveryCompatForge
java.lang.IllegalStateException: Bus is null. You must call RegHelper.startRegistering(IEventBus) before registering events
	at TRANSFORMER/moonlight@1.21-2.15.6/net.mehvahdjukaar.moonlight.neoforge.MoonlightForge.getCurrentBus(MoonlightForge.java:167) ~[moonlight-1.21-2.15.6-neoforge.jar#583!/:?]
	at TRANSFORMER/moonlight@1.21-2.15.6/net.mehvahdjukaar.moonlight.api.platform.network.neoforge.NetworkHelperImpl.addNetworkRegistration(NetworkHelperImpl.java:62) ~[moonlight-1.21-2.15.6-neoforge.jar#583!/:?]
	at TRANSFORMER/moonlight@1.21-2.15.6/net.mehvahdjukaar.moonlight.api.platform.network.NetworkHelper.addNetworkRegistration(NetworkHelper.java) ~[moonlight-1.21-2.15.6-neoforge.jar#583!/:?]
	at TRANSFORMER/everycomp@1.21-2.7.2/net.mehvahdjukaar.every_compat.ECNetworking.init(ECNetworking.java:26) ~[everycomp-1.21-2.7.2-neoforge.jar#504!/:?]
	at TRANSFORMER/everycomp@1.21-2.7.2/net.mehvahdjukaar.every_compat.EveryCompat.commonInit(EveryCompat.java:93) ~[everycomp-1.21-2.7.2-neoforge.jar#504!/:?]
	at TRANSFORMER/everycomp@1.21-2.7.2/net.mehvahdjukaar.every_compat.neoforge.EveryCompatForge.<init>(EveryCompatForge.java:70) ~[everycomp-1.21-2.7.2-neoforge.jar#504!/:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.31.jar#175!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.31.jar#175!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.31.jar#175!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by ToxinZangoose** [comment]
I see, thank you. I will try the newest update for owo and see if this resolves the issue.

**Comment by ToxinZangoose** [comment]
Alright, tested this again with Accessories and owo and it works!
Although when adding Every Compat, it seems to still crash, but I found that was an unrelated bug/incompatibility with Colossal Chests.

**Comment by ToxinZangoose** [comment]
Everything works perfectly now, closing this as complete. :)
