### ISSUE TITLE
Crash with mixin debug 

### ISSUE THREAD

**Issue by SettingDust** [wisp-forest/owo-lib#34]
```
[22:44:22] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod owo failed owo.mixins.json:MinecraftClientMixin from mod owo -> net.minecraft.class_310: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Injection validation failed: Callback method afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in owo.mixins.json:MinecraftClientMixin from mod owo expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap owo-lib-refmap.json [INJECT Applicator Phase -> owo.mixins.json:MinecraftClientMixin from mod owo -> Apply Injections ->  -> PostInject -> owo.mixins.json:MinecraftClientMixin from mod owo->@Inject::afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in owo.mixins.json:MinecraftClientMixin from mod owo expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap owo-lib-refmap.json [INJECT Applicator Phase -> owo.mixins.json:MinecraftClientMixin from mod owo -> Apply Injections ->  -> PostInject -> owo.mixins.json:MinecraftClientMixin from mod owo->@Inject::afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at net.minecraft.class_6396.handler$flf000$patchouli_addContext(class_6396.java:1516)
	at net.minecraft.class_6396.<init>(class_6396.java:57)
	at net.minecraft.class_128.<init>(class_128.java:32)
	at net.minecraft.class_128.method_24305(class_128.java:272)
	at net.minecraft.client.main.Main.main(Main.java:151)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[22:44:22] [main/ERROR] (FabricLoader) Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at net.minecraft.class_6396.handler$flf000$patchouli_addContext(class_6396.java:1516)
	at net.minecraft.class_6396.<init>(class_6396.java:57)
	at net.minecraft.class_128.<init>(class_128.java:32)
	at net.minecraft.class_128.method_24305(class_128.java:272)
	at net.minecraft.client.main.Main.main(Main.java:151)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [owo.mixins.json:MinecraftClientMixin from mod owo] from phase [DEFAULT] in config [owo.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in owo.mixins.json:MinecraftClientMixin from mod owo expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap owo-lib-refmap.json [INJECT Applicator Phase -> owo.mixins.json:MinecraftClientMixin from mod owo -> Apply Injections ->  -> PostInject -> owo.mixins.json:MinecraftClientMixin from mod owo->@Inject::afterQuiltHook(Lnet/minecraft/class_542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more
```

**Comment by gliscowo** [comment]
I assume you're using mixin's `-Dmixin.debug` flag directly, which will enable all debug features - including strict injection checks. This will break more than just owo, a middle-size modpack will basically never launch with this flag enabled. You're probably looking to enable on of the [sub options](https://github.com/SpongePowered/Mixin/wiki/Mixin-Java-System-Properties), most commonly `-Dmixin.debug.export` and `-Dmixin.debug.verbose`
Cheers
