### ISSUE TITLE
[Version 0.10.0 for 1.19.3] Incompatibility with blur (fabric)

### ISSUE THREAD

**Issue by Sermegshimin** [wisp-forest/owo-lib#82]
After the update, installing these 2 mods together results in endless "mojang studios" loading screen. It can be fixed by a reversion to 0.9.3 version
HOW TO REPRODUCE:
1)On a clear installation install both blur and the latest owo-lib
2)Run minecraft
3)Witness the infinity!

![unknown_2023 01 18-16 31](https://user-images.githubusercontent.com/122805504/213184506-e4a06987-c578-4055-9d63-f4857120b15c.png)

https://user-images.githubusercontent.com/122805504/213185077-1728af34-4515-4b9e-b340-fb45e65e7cc0.mp4

**Comment by BasiqueEvangelist** [comment]
Here's the actual error
I love ShaderProgram :smiling_face_with_three_hearts:
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to initialized owo shader program
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1144) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialized owo shader program
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:51) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.md546a58$lambda$loadAllTheShaders$0$0(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zlb000$loadAllTheShaders(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.loadPrograms(GameRenderer.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 16 more
Caused by: net.minecraft.util.InvalidHierarchicalFileException: Invalid shaders/core/spectrum.json: File not found
	at net.minecraft.util.InvalidHierarchicalFileException.wrap(InvalidHierarchicalFileException.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.client.gl.ShaderProgram.<init>(ShaderProgram.java:201) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.md546a58$lambda$loadAllTheShaders$0$0(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zlb000$loadAllTheShaders(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.loadPrograms(GameRenderer.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 16 more
Caused by: java.io.FileNotFoundException: owo:shaders/core/shaders/core/spectrum.fsh
	at net.minecraft.resource.ResourceFactory.method_43043(ResourceFactory.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.resource.ResourceFactory.getResourceOrThrow(ResourceFactory.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.client.gl.ShaderProgram.loadShader(ShaderProgram.java:236) ~[client-intermediary.jar:?]
	at net.minecraft.client.gl.ShaderProgram.<init>(ShaderProgram.java:184) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.md546a58$lambda$loadAllTheShaders$0$0(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.0+1.19.3.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zlb000$loadAllTheShaders(GameRenderer.java:2076) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.loadPrograms(GameRenderer.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer$1.apply(GameRenderer.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 16 more
```

**Comment by Sermegshimin** [comment]
Yeah, something is always wrong. I understand your feelings.
