### ISSUE TITLE
[Version 0.10.1 for 1.19.3] Incompatibility with Xaero's Minimap

### ISSUE THREAD

**Issue by iblowmymind** [wisp-forest/owo-lib#83]
```
[18:48:23] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[18:48:25] [Render thread/WARN]: Mixin transformation of net.minecraft.class_5944 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:278) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:153) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at xaero.common.graphics.CustomVertexConsumers.lambda$new$0(CustomVertexConsumers.java:13) ~[Xaeros_Minimap_22.17.1_Fabric_1.19.3.jar:?]
	at net.minecraft.class_156.method_654(class_156.java:440) ~[client-intermediary.jar:?]
	at xaero.common.graphics.CustomVertexConsumers.<init>(CustomVertexConsumers.java:12) ~[Xaeros_Minimap_22.17.1_Fabric_1.19.3.jar:?]
	at xaero.common.interfaces.render.InterfaceRenderer.<init>(InterfaceRenderer.java:34) ~[Xaeros_Minimap_22.17.1_Fabric_1.19.3.jar:?]
	at xaero.minimap.XaeroMinimap.loadClient(XaeroMinimap.java:203) ~[Xaeros_Minimap_22.17.1_Fabric_1.19.3.jar:?]
	at xaero.minimap.XaeroMinimap.onInitializeClient(XaeroMinimap.java:63) ~[Xaeros_Minimap_22.17.1_Fabric_1.19.3.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:53) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[quilt-loader-0.17.10.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:465) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) ~[quilt-loader-0.17.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) ~[quilt-loader-0.17.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method fixIdentifier(Ljava/lang/String;)Ljava/lang/String; in owo.mixins.json:shader.ShaderProgramMixin from mod owo failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap owo-lib-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	... 29 more
```

Steps to reproduce:
- Install 1.19.3 + Quilt
- Install owo-lib and Xaero's Minimap
- Witness the crash!

Another shader program crash?

**Comment by gliscowo** [comment]
I am unable to reproduce this with only Xaero's Minimap installed, can you send us the entire log so we can investigate this more thoroughly?

**Comment by byquanton** [comment]
I guess it's Satin + owolib.

**Comment by gliscowo** [comment]
While we can't be 100% sure, this should now be fixed in [0.10.2](https://modrinth.com/mod/owo-lib/version/KMwbSA7v)
Cheers

**Comment by iblowmymind** [comment]
Hello,
Sorry for not noticing your comment!
I'll try and see if it fixed or not.

**Comment by iblowmymind** [comment]
Yup, that seems to have fixed it. Closing the issue. Thank you!
