### ISSUE TITLE
Player crashed and cant log back in

### ISSUE THREAD

**Issue by gamerpotion** [wisp-forest/owo-lib#99]
Hi, a player of my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
has reported that they keep getting constant error as per below and cant login any more, whenever they load the game it shows the following

![image](https://user-images.githubusercontent.com/88756564/220700106-222917ee-6a15-4355-989f-92f551f3cab3.png)

```---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-02-22 15:21:43
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.minecraft.class_1921.method_23012(class_1921.java:751)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:75)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:72)
	at net.minecraft.class_327.method_22941(class_327.java:117)
	at net.minecraft.class_327.method_27517(class_327.java:77)
	at io.wispforest.owo.ui.util.UIErrorToast.method_1986(UIErrorToast.java:64)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:154)
	at net.minecraft.class_374.method_45074(class_374.java:38)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:37)
	at net.minecraft.class_310.method_1523(class_310.java:1195)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.minecraft.class_1921.method_23012(class_1921.java:751)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:75)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:72)
	at net.minecraft.class_327.method_22941(class_327.java:117)
	at net.minecraft.class_327.method_27517(class_327.java:77)
	at io.wispforest.owo.ui.util.UIErrorToast.method_1986(UIErrorToast.java:64)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:154)
	at net.minecraft.class_374.method_45074(class_374.java:38)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, Fabric Mods, file/Gothic RPG Font.zip, simplyswords/classic
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 722686320 bytes (689 MiB) / 1654652928 bytes (1578 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f0a
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28110.91
	Virtual memory used (MB): 16116.84
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 55.29
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		adabranium: Adabranium 2.4.0+1.19.3
		adorn: Adorn 4.0.1+1.19.3
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		alloy_forgery: Alloy Forgery 2.0.19+1.19.3
		amethyst_core: Amethyst Core 1.0.4+1.19.3
		amethyst_imbuement: Amethyst Imbuement 1.19.3-05
			playerabilitylib: Pal 1.7.0
			structurized-reborn: Structurized Reborn 1.19.3-01
		amethystequipment: Amethyst Equipment 1.0.7
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.70
		balm-fabric: Balm 5.0.2
		betteradvancements: Better Advancements 0.3.1.149
		betterf3: BetterF3 5.1.0
		bhmenu: BHMenu-Fabric 1.19.3-1.3
		block_limit_fix: Block Limit Fix 1.0.3-fabric
		boatoverhaul: BoatOverhaul 2.0.0
		boneequipment: Bone Equipment 1.0.6
		bookshelf: Bookshelf 17.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.5.1-1.19.3
			maelstrom_library: Maelstrom Library 1.4-1.19.3-rc1
			multipart_entities: MultipartEntities 1.3-1.19.3-rc1
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		castleblocks: CastleBlocks 1.21
		chunksfadein: Chunks Fade In 2.0.10-1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cinderscapes: Cinderscapes 3.1.0
			cinderscapes-client: Cinderscapes: Client 3.1.0
			cinderscapes-common: Cinderscapes: Common 3.1.0
			cinderscapes-worldgen: Cinderscapes: World Generation 3.1.0
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 5.0.0-beta.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 5.0.0-beta.1
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		clickadv: Clickable Advancements Mod 3.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		collective: Collective 6.48
		configured: Configured 2.0.2
		controlling: Controlling For Fabric 10.0+9
		cosmetica: Cosmetica 1.2.3
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.10.0
			sulphate: Sulfate 1.1.1
		crawl: Crawl 0.11.5
			mm: Manningham Mills 2.3
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkbindings: DarkBindings - Custom Recipes 1.2.3
		darkcap: DarkCap - Cap Your XP! 1.0.2
		darkflight: DarkFlight - Simple Jetpack 1.0.3
		darkinventory: DarkInventory - Keep Inventory On 1.0.0
		darkloot: DarkLoot - Better Mob Loot 1.0.9
		darkmenu: DarkMenu - DarkRPG Legacy Menu 1.0.2
		darkmining: DarkMining - Better Block Drops 1.0.3
		darkquesting: DarkQuesting - A Quest Mod 1.1.0
		darkrtp: DarkRTP - RTP Teleport 1.0.3
		darkspawn: DarkSpawn - Teleport to Spawn 1.0.0
		darkspins: DarkSpins - XP Casino 1.0.3
		darkstarter: DarkStarter - Starter Items 1.0.0
		darktides: DarkTides - Breathe Underwater 1.0.7
		darkwooly: DarkWooly - Get More Wool 1.0.1
		dawn: Dawn API 4.1.1
		diamondeconomy: Diamond Economy 1.5.4
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
		diamondsauctionhouse: Diamond Auction House 1.1.41.19.3
			sgui: sgui 1.2.1+1.19.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dragonloot: DragonLoot 1.1.3
		durability101: Durability101 0.0.4
		emerald_tools: Emerald Tools 1.5.7
			pugh_tools: Pugh Tools 1.4.7
		enchanting-table-descriptions: Enchanting Table Descriptions 0.1.0+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		enchdesc: EnchantmentDescriptions 14.0.4
		exordium: Exordium 1.0.3-mc1.19.3
		extraalchemy: Extra Alchemy 1.9.2
		extraorigins: Extra Origins 1.19-3
		fabric-api: Fabric API 0.74.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.30+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.0+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.1+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.30+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.33+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+eb2a3ba985
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		farsight: Farsight Mod 1.19-3.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		ferritecore: FerriteCore 5.1.0
		foxboi_two: Kitsune 1.1.9
		fzzy_core: Fzzy Core 0.1.2+1.19.3
		gear_core: Gear Core 0.1.3+1.19.3
		gearifiers: Gearifiers 0.1.4+1.19.3
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		geckolib: Geckolib 4.0.3
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.19.3-1.3
		globalpacks: Global Data- & Resourcepacks 1.15.3_fabric
		goml: Get Off My Lawn ReServed 1.7.0+1.19.3
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			hologram-api: Hologram API 0.2.3+1.19.3
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		halohud: Halo HUD 1.1+1.19.3
		handcrafted: Handcrafted 2.0.4
		harvest_scythes: Harvest Scythes 2.5.5+mc1.19.3
		healingcampfire: Healing Campfire 5.1
		healthcare: Health Care 1.2.1
			config2brigadier: Config to Brigadier 1.2.1
			server_translations_api: Server Translations API 1.4.19+1.19.3
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		healthoverlay: Health Overlay 8.0.3
			fiber: fiber 0.23.0-2
		immersive_aircraft: Immersive Aircraft 0.3.0+1.19.3
		immersive_armors: Immersive Armors 1.5.4+1.19.3
		inventoryprofilesnext: Inventory Profiles Next 1.9.2
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ironchests: Iron Chests 1.7.8
			libgui: LibGui 6.5.0+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 9.3.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 12.2.0.17
		journeymap: Journeymap 5.9.3
			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libipn: libIPN 2.0.2
		limitedspawners: Limited Spawner 1.0.6
		lithium: Lithium 0.10.4
		logical_zoom: Logical Zoom 0.0.18
		lootr: Lootr 0.4.25.65
		magistuarmory: Epic Knights Mod 7.6
		maxhealthfix: MaxHealthFix 9.0.1
		minecraft: Minecraft 1.19.3
		mo_glass: Mo Glass 1.6.1-MC1.19.3
		modmenu: Mod Menu 5.0.2
		more_gems: More Gems 1.5.7
		mousetweaks: Mouse Tweaks 2.24
		mythicmetals: Mythic Metals 0.17.2+1.19.3
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.3
		mythicupgrades: Mythic Upgrades +fabric-1.6-BetaPreview3-1.19.3
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.1
		origins: Origins 1.8.1
			apoli: Apoli 2.7.1
				calio: Calio 1.8.0
		origins-classes: Origins: Classes 1.5.0
		owo: oωo 0.10.2+1.19.3
			blue_endless_jankson: jankson 1.2.1
		pack_it_up: Pack It Up! 0.3.0+1.19.3
		painters_blocks_wrapper: Painter's Blocks 2.0.0+1.19.3
			painters_blocks: Painter's Blocks 2.0.0+1.19.3
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pfm: Paladin's Furniture 1.1.2
		promenade: Promenade 3.1.0
		random_ring: Random Ring 1.2.6
		redmorestructure: Reds More Structures 1.0.5-fabric-1.19.3
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		servercore: ServerCore 1.3.4-1.19.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		simplyswords: Simply Swords 1.43.0-1.19.3
		sit: Sit 1.19.3-22
		smoothboot: Smooth Boot 1.19-1.7.1
		smwyg: Show Me What You Got 1.1.0
		sodium: Sodium 0.4.9+build.23
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		stacker: Stacker 3.0.2-1.19.3
			stacc: Stacc 1.4.0
		starlight: Starlight 1.1.1+fabric.ae22326
		t_and_t: Towns and Towers 1.10.1
		terrablender: TerraBlender 2.1.0.134
		terrestria: Terrestria 5.1.1
			terraform-config-api-v1: Terraform Config API (v1) 5.0.0-beta.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 5.0.0-beta.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 5.0.0-beta.1
			terraform-tree-api-v1: Terraform Tree API (v1) 5.0.0-beta.1
			terrestria-client: Terrestria: Client 5.1.1
			terrestria-common: Terrestria: Common 5.1.1
			terrestria-worldgen: Terrestria: World Generation 5.1.1
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.0+1.19.3
		timeoutout: TimeOut Out 1.0.3+1.19.1
		tipsmod: Tips 9.0.3
		toofast: TooFast 1.0.0
		toolstats: ToolStats 13.0.1
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		traverse: Traverse 6.1.2
			traverse-client: Traverse: Client 6.1.2
			traverse-common: Traverse: Common 6.1.2
			traverse-worldgen: Traverse: World Generation 6.1.2
		trinkets: Trinkets 3.5.1
		universal_shops: Universal Shops 1.1.2+1.19.3
			common-economy-api: Common Economy API 1.0.0
			placeholder-api: Placeholder API 2.0.0-pre.4+1.19.3
			polymer-core: Polymer (Core) 0.3.5+1.19.3
				polymer-networking: Polymer (Networking) 0.3.5+1.19.3
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.3.5+1.19.3
			polymer-resource-pack: Polymer (Resource Pack) 0.3.5+1.19.3
				polymer-common: Polymer (Common) 0.3.5+1.19.3
		vanityslots: Vanity Slots 1.2.5
		waystones: Waystones 12.0.2
		yosbr: YOSBR 0.1.1
	Loaded Shaderpack: BSL_v8.1.02.1.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.14-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Gothic RPG Font.zip (incompatible), simplyswords:classic
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor ```

**Comment by gliscowo** [comment]
This issue simply does not contain enough information for us to even begin trying to resolve it. We (and you as well, I gather?) have no way of replicating it, which would be an essential first step. Also, in general, it is always advisable to send the entire log and not just the crash report.

I'd ask you to go back to your user and ask them whether they can provide us with more information on when and how this occurs (and potentially how we may try and reproduce it), as well as their entire `latest.log` file

Cheers
